# Generated by Django 4.2 on 2023-04-13 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("voice_assistant", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "settings",
                "verbose_name_plural": "settings",
                "db_table": "Settings",
            },
        ),
    ]
