# Generated by Django 3.2.4 on 2021-06-30 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='authentication.user')),
                ('dark_color_value', models.CharField(blank=True, default='Black', max_length=500, null=True)),
                ('light_color_value', models.CharField(blank=True, default='White', max_length=500, null=True)),
                ('voice_assistant', models.BooleanField(default=True)),
                ('use_numpad_keys_for_movement', models.BooleanField(default=True, verbose_name='use numpad keys for movement of pieces')),
            ],
            options={
                'db_table': 'Settings',
            },
        ),
    ]
