# Generated by Django 4.1.1 on 2023-01-29 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
