# Generated by Django 4.2 on 2023-05-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_birth_date"),
        ("authentication", "0002_remove_user_id_alter_user_email"),
    ]

    operations = []
