# Generated by Django 3.0.7 on 2020-08-22 06:29

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200822_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_pin',
            field=models.CharField(default=None, max_length=20, null=True, unique=True, validators=[
                                   authentication.validators.validate_isnumeric]),
        ),
    ]
